### PR TITLE
Fixed issue in read_dex_string

### LINKED ISSUE #152: The Python binding may extract strings incompletely
**Describe the bug**

Hi! Thank you for the quick patch for #145. I investigated further and found that some strings extracted by the Python binding appear incomplete.

By disassembling method Lcom/google/progress/AndroidClientService$1;->onCallStateChanged(ILjava/lang/String;)V in [this APK](https://github.com/quark-engine/apk-samples/blob/master/malware-samples/14d9f1a92dd984d6040cc41ed06e273e.apk), I get instruction `const-string v4, "手机\xe7\x8a" // string@4272` at index 3. The instruction references the string "手机\xe7\x8a".
```python
>>> from shuriken import Apk
>>> apk = Apk("14d9f1a92dd984d6040cc41ed06e273e.apk", create_xrefs=True)
>>> method = apk.get_disassembled_method_from_apk("Lcom/google/progress/AndroidClientService$1;->onCallStateChanged(ILjava/lang/String;)V")
>>> disassembly = method.instructions[3].disassembly.decode(errors="backslashreplace")
>>> print(disassembly)
const-string v4, "手机\xe7\x8a" // string@4272
```

However, according to dexdump and Androguard, the instruction is `const-string v4, "手机状态发生改变"`. The string is "手机状态发生改变".
```
$ unzip -j 14d9f1a92dd984d6040cc41ed06e273e.apk classes.dex
$ dexdump -d classes.dex | grep -B 4 "01264a"
01262c:                                        |[01262c] com.google.progress.AndroidClientService$1.onCallStateChanged:(ILjava/lang/String;)V
01263c: 5473 5c00                              |0000: iget-object v3, v7, Lcom/google/progress/AndroidClientService$1;.this$0:Lcom/google/progress/AndroidClientService; // field@005c
012640: 6e10 8501 0300                         |0002: invoke-virtual {v3}, Lcom/google/progress/AndroidClientService;.getRingAudio:()V // method@0185
012646: 1a03 1009                              |0005: const-string v3, "call" // string@0910
01264a: 1a04 b010                              |0007: const-string v4, "手机状态发生改变" // string@10b0
```

```python
>>> from androguard.misc import AnalyzeAPK
>>> _, _, analysis = AnalyzeAPK("14d9f1a92dd984d6040cc41ed06e273e.apk")
>>> method = next(analysis.find_methods("Lcom/google/progress/AndroidClientService\$1;","onCallStateChanged"))
>>> disassembly = str(list(method.get_method().get_instructions())[3])
>>> print(disassembly)
const-string v4, "手机状态发生改变"
```

**To Reproduce**

1. Put [this APK](https://github.com/quark-engine/apk-samples/blob/master/malware-samples/14d9f1a92dd984d6040cc41ed06e273e.apk) in the current working directory.
2. Run the following scripts to get the instructions from the Python binding and Androguard.
```python
from shuriken import Apk
apk = Apk("14d9f1a92dd984d6040cc41ed06e273e.apk", create_xrefs=True)
method = apk.get_disassembled_method_from_apk("Lcom/google/progress/AndroidClientService$1;->onCallStateChanged(ILjava/lang/String;)V")
disassembly = method.instructions[3].disassembly.decode(errors="backslashreplace")
print(disassembly)
```

```python
from androguard.misc import AnalyzeAPK
_, _, analysis = AnalyzeAPK("14d9f1a92dd984d6040cc41ed06e273e.apk")
method = next(analysis.find_methods("Lcom/google/progress/AndroidClientService\$1;","onCallStateChanged"))
disassembly = str(list(method.get_method().get_instructions())[3])
print(disassembly)
```

3. Run the following command to get the instruction from dexdump.
```
unzip -j 14d9f1a92dd984d6040cc41ed06e273e.apk classes.dex
dexdump -d classes.dex | grep -B 4 "01264a"
```

**Expected behavior**

Since CJK characters are typically encoded in multiple bytes and "手机\xe7\x8a" matches the initial 8 bytes of  "手机状态发生改变" exactly, I doubt the Python binding didn't extract enough bytes to get the entire string. However, please feel free to correct me if I've missed something.

### PR DESCRIPTION
**Pull request by Fare9**
Closes #152

### CODE REVIEW

**Comment by Fare9** [comment]
# Unicode String Support in DEX String Reading

Fix for proper handling of Unicode strings in DEX files.

## Issue
The previous implementation incorrectly used the ULEB128 length value (which represents UTF-16 code units) to determine how many bytes to read. This caused corruption when reading strings with non-ASCII characters.

## Solution
Modified string reading to properly handle MUTF-8 encoded strings by:
- Reading all bytes until encountering a null terminator (0x00)
- Properly interpreting multi-byte character sequences
- Marking the UTF-16 length as `[[maybe_unused]]` since we rely on null-termination instead

## Impact
- Correctly displays all Unicode characters, including CJK characters
- Improves compatibility with international applications
- Maintains accurate string representation during disassembly

This change is essential for accurate reverse engineering of Android applications targeting global markets, where Unicode text is common.

File: shuriken/lib/common/shurikenstream.cpp [hunk 1]
```diff
@@ -103,23 +103,22 @@ std::string ShurikenStream::read_ansii_string(std::int64_t offset) {
...
-        new_str += static_cast<char>(character);
+    
+    // Read ULEB128 size (this is the length in UTF-16 code units)
+    [[maybe_unused]] std::uint64_t utf16_size = read_uleb128();
+    
+    // Read all bytes until null terminator
+    std::string new_str;
+    char character;
+    while (input_file.read(&character, 1) && character != 0) {
+        new_str.push_back(character);
```
Comment (badumbatish) [inline shuriken/lib/common/shurikenstream.cpp:119]: we can try  `std::getline(input_file, new_str, 0);` maybe?

Comment (Fare9) [reply shuriken/lib/common/shurikenstream.cpp:119]: hmmm for the moment could be, but with the current way we could put a limit in the future if we want to set a reading limit to avoid buffer overflows.
